version: "3.7"
services:
  shift-hls-stream:
    image: nhkrecord/shift-hls-stream:latest
    restart: unless-stopped
    volumes:
      - "data:/data/"
    environment:
      - "STREAM_URL=https://b-nhkwlive-ojp.webcdn.stream.ne.jp/hls/live/2003459-b/nhkwlive-ojp-en/index_4M.m3u8"
      - "STREAM_DELAY=3600"
      - "MAX_AGE=7200"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "9898:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "data:/docroot/"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  data:
